import { beforeEach, test } from 'node:test';
import assert from 'node:assert/strict';
import * as api from '../../server/store';
import { reviewDateBounds } from './scoring';
import { sources } from '../data/scenario';
function unwrap<T>(result: api.Result<T>): T { if (!result.ok) assert.fail(result.error.message); return result.data; }
function denied(result: api.Result<unknown>, code: api.ApiError['code']) { assert.equal(result.ok, false); if (!result.ok) assert.equal(result.error.code, code); }
function signIn(role: 'reader' | 'reviewer' | 'admin') { const passwords = { reader: 'ReaderDemo!', reviewer: 'ReviewerDemo!', admin: 'AdminDemo!' }; return unwrap(api.login(`${role}@trustlens.demo`, passwords[role])); }
function input(overrides: Partial<api.ValidationInput> = {}): api.ValidationInput { return { questionId: 'ticket-a', sourceId: 's1', claim: sources[0].claim, owner: 'Marie Dubois', reason: 'Approved policy applies to this customer.', reviewBy: reviewDateBounds().min, ...overrides }; }
beforeEach(() => { signIn('admin'); unwrap(api.resetDemo()); api.logout(); });
test('login compares mock hashes and session role/tenant are immutable', () => { denied(api.login('admin@trustlens.demo', 'bad'), 'UNAUTHENTICATED'); const session = signIn('reviewer'); assert.equal(session.role, 'Reviewer'); assert.equal(session.tenantId, 'acme'); assert.throws(() => { session.role = 'Admin'; }); assert.throws(() => { session.capabilities.canViewAudit = true; }); assert.equal(api.getSession()?.role, 'Reviewer'); api.logout(); assert.equal(api.getSession(), null); });
test('protected reads and actions require a session', () => { denied(api.getScenario(), 'UNAUTHENTICATED'); denied(api.getSources('ticket-a'), 'UNAUTHENTICATED'); denied(api.validateAnswer(input()), 'UNAUTHENTICATED'); });
test('Reader cannot directly validate, escalate, resolve, reset or retrieve audit', () => { signIn('reader'); unwrap(api.getSources('ticket-a')); unwrap(api.getVerifiedCards('ticket-b')); denied(api.validateAnswer(input()), 'FORBIDDEN'); denied(api.escalate('ticket-a', 's1', 'Review this'), 'FORBIDDEN'); denied(api.resolveEscalation('ticket-b', 'unknown', 'b-s1', 'Review this'), 'FORBIDDEN'); denied(api.getAuditLog('ticket-a'), 'FORBIDDEN'); denied(api.resetDemo(), 'FORBIDDEN'); });
test('Reviewer actions are allowed but full audit is denied; Admin reads audit', () => { signIn('reviewer'); unwrap(api.validateAnswer(input())); denied(api.getAuditLog('ticket-a'), 'FORBIDDEN'); api.logout(); signIn('admin'); assert.equal(unwrap(api.getAuditLog('ticket-a')).length, 1); });
test('real foreign question/source/card/escalation IDs cannot be read or used', () => { signIn('admin'); denied(api.getScenario('other-ticket'), 'NOT_FOUND'); denied(api.getSources('ticket-a', 'other-source'), 'NOT_FOUND'); denied(api.getVerifiedCards('ticket-a', 'other-card'), 'NOT_FOUND'); denied(api.validateAnswer(input({ sourceId: 'other-source' })), 'NOT_FOUND'); denied(api.escalate('ticket-a', 'other-source', 'Owner review'), 'NOT_FOUND'); denied(api.resolveEscalation('ticket-a', 'other-escalation', 's1', 'Owner reviewed'), 'NOT_FOUND'); denied(api.getAuditLog('other-ticket'), 'NOT_FOUND'); assert.equal(unwrap(api.getScenario()).tickets.length, 2); });
test('cross-question and unknown IDs fail closed, including empty lookup IDs', () => { signIn('reviewer'); denied(api.getSources('ticket-a', 'b-s1'), 'NOT_FOUND'); denied(api.getVerifiedCards('ticket-a', 'b-expired-card'), 'NOT_FOUND'); denied(api.getSources('ticket-a', ''), 'NOT_FOUND'); denied(api.getVerifiedCards('ticket-b', ''), 'NOT_FOUND'); denied(api.getScenario('missing'), 'NOT_FOUND'); denied(api.validateAnswer(input({ sourceId: 'missing' })), 'NOT_FOUND'); denied(api.validateAnswer(input({ questionId: 'ticket-b' })), 'NOT_FOUND'); });
test('validation rejects short/long reason, empty/mismatched claim, wrong owner and invalid dates', () => { signIn('reviewer'); const bounds = reviewDateBounds(); const today = new Date(bounds.min + 'T00:00:00Z'); today.setUTCDate(today.getUTCDate() - 1); for (const change of [{ reason: ' x ' }, { reason: 'x'.repeat(501) }, { claim: '' }, { claim: 'Made-up unrelated claim' }, { owner: 'Someone else' }, { reviewBy: today.toISOString().slice(0, 10) }, { reviewBy: '2026-02-30' }, { reviewBy: '9999-01-01' }]) denied(api.validateAnswer(input(change)), 'INVALID_INPUT'); assert.equal(unwrap(api.getVerifiedCards('ticket-a')).length, 0); });
test('validation accepts trimmed boundary reasons and a review exactly 24 months away', () => { signIn('reviewer'); const card = unwrap(api.validateAnswer(input({ reason: '  Yes  ', reviewBy: reviewDateBounds().max }))); assert.equal(card.reason, 'Yes'); assert.equal(card.tenantId, 'acme'); assert.equal(card.questionId, 'ticket-a'); });
test('Ticket B requires escalation then resolution before validation; verified card is reused', () => { signIn('reviewer'); const bInput = input({ questionId: 'ticket-b', sourceId: 'b-s1', owner: 'Sofie Claes', claim: unwrap(api.getSources('ticket-b', 'b-s1'))[0].claim }); denied(api.validateAnswer(bInput), 'CONFLICT'); const escalation = unwrap(api.escalate('ticket-b', 'b-s1', 'Resolve current disagreement')); denied(api.escalate('ticket-b', 'b-s1', 'Duplicate request'), 'CONFLICT'); unwrap(api.resolveEscalation('ticket-b', escalation.id, 'b-s1', 'Owner confirms prior written approval applies.')); assert.equal(unwrap(api.getScenario('ticket-b')).evaluation.canValidate, true); const card = unwrap(api.validateAnswer(bInput)); const result = unwrap(api.getScenario('ticket-b')); assert.equal(result.evaluation.top?.id, card.id); assert.equal(result.evaluation.factors[card.id].authority, 100); assert.equal(result.evaluation.state, 'confident'); assert.equal(result.evaluation.conflictCount, 0); assert.equal(result.cards.length, 2); });
test('expired cards and invalid sources cannot be escalated or validated as authority', () => { signIn('reviewer'); denied(api.escalate('ticket-b', 'b-expired-card', 'Review again'), 'CONFLICT'); denied(api.validateAnswer(input({ sourceId: 's2', claim: unwrap(api.getSources('ticket-a', 's2'))[0].claim, owner: 'HR Ops Archive' })), 'CONFLICT'); });
test('a later owner resolution and verified answer supersede an earlier verified answer', () => { signIn('reviewer'); for (const sourceId of ['b-s1', 'b-s2']) { const source = unwrap(api.getSources('ticket-b', sourceId))[0]; const escalation = unwrap(api.escalate('ticket-b', sourceId, 'Owner requests a current clause review.')); unwrap(api.resolveEscalation('ticket-b', escalation.id, sourceId, 'Owner confirms this clause applies.')); const card = unwrap(api.validateAnswer(input({ questionId: 'ticket-b', sourceId, owner: source.owner!, claim: source.claim }))); assert.equal(unwrap(api.getScenario('ticket-b')).evaluation.top?.id, card.id); } });
test('audit snapshots are frozen, chained deterministically and tenant/question-scoped', () => { signIn('admin'); unwrap(api.escalate('ticket-a', 's1', 'Please review')); const escalation = unwrap(api.getScenario()).escalation!; unwrap(api.resolveEscalation('ticket-a', escalation.id, 's1', 'Owner confirms filing requirement.')); unwrap(api.validateAnswer(input())); const entries = unwrap(api.getAuditLog('ticket-a')); assert.equal(entries.length, 3); assert.ok(Object.isFrozen(entries)); for (let i = 0; i < entries.length; i++) { const { hash, ...payload } = entries[i]; assert.ok(Object.isFrozen(entries[i])); assert.equal(hash, api.demoHash(api.canonicalPayload(payload))); assert.equal(entries[i].previousHash, i ? entries[i - 1].hash : '00000000'); assert.equal(entries[i].tenantId, 'acme'); assert.equal(entries[i].questionId, 'ticket-a'); } assert.throws(() => { entries[0].reason = 'tampered'; }); assert.throws(() => entries.pop()); assert.equal(unwrap(api.getAuditLog('ticket-b')).length, 0); });
test('service read snapshots cannot mutate the underlying store', () => { signIn('reviewer'); const snapshot = unwrap(api.getScenario()); assert.throws(() => { snapshot.sources[0].factors.authority = 0; }); assert.throws(() => { snapshot.question.context.countryCode = 'FR'; }); assert.equal(unwrap(api.getScenario()).evaluation.top?.id, 's1'); });
test('reset restores seeds, clears tenant review history, and retains account identity', () => { signIn('admin'); unwrap(api.validateAnswer(input())); unwrap(api.escalate('ticket-b', 'b-s1', 'Owner review')); unwrap(api.resetDemo()); assert.equal(unwrap(api.getVerifiedCards('ticket-a')).length, 0); assert.equal(unwrap(api.getVerifiedCards('ticket-b')).length, 1); assert.equal(unwrap(api.getAuditLog('ticket-a')).length, 0); assert.equal(unwrap(api.getScenario('ticket-b')).escalation, undefined); assert.equal(api.getSession()?.role, 'Admin'); });

