import { useState, type FormEvent } from 'react';
import type { Session, Source } from '../data/scenario';
import type { DecisionSnapshot } from '../lib/api';
import { QuestionCard } from '../components/QuestionCard';
import { SourceCard } from '../components/SourceCard';
import { KnowledgeDiff } from '../components/KnowledgeDiff';
import { TrustBreakdown } from '../components/TrustBreakdown';
import { RecommendationBanner } from '../components/RecommendationBanner';
export function Decision({ data, selected, select, session, onTicket, onReset, onEscalate, onResolve, onValidate, inspect }: { data: DecisionSnapshot; selected?: Source; select: (s: Source) => void; session: Session; onTicket: (id: string) => void; onReset: () => void; onEscalate: () => void; onResolve: (sourceId: string, reason: string) => void; onValidate: () => void; inspect: (s: Source) => void }) {
  const [resolutionSource, setResolutionSource] = useState(''); const result = data.evaluation;
  function resolve(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); onResolve(String(form.get('sourceId')), String(form.get('reason'))); }
  return <><QuestionCard question={data.question} tickets={data.tickets} result={result} count={data.sources.length} onTicket={onTicket} onReset={onReset} canReset={session.capabilities.canReset} /><div className="decision-grid"><section className="sources-column" aria-labelledby="sources-heading"><div className="column-heading"><h2 id="sources-heading">Source documents</h2><span className="found-badge">{data.sources.length} found</span></div><div className="source-list" key={data.question.id}>{!data.sources.length && <p className="empty-evidence">No source excerpts loaded. Find knowledge to retrieve available evidence.</p>}{data.sources.map(source => <SourceCard key={source.id} source={source} selected={source.id === selected?.id} onSelect={() => select(source)} value={result.scores[source.id]} factors={result.factors[source.id]} excluded={result.excludedSources.some(e => e.source.id === source.id)} />)}</div></section><div className="diff-column"><div className="column-heading"><h2>Legal redline</h2><span className={result.conflictCount ? 'conflict-badge' : 'analysis-label'}>{result.conflictCount ? '↔ Unresolved conflict' : result.flags[0] ?? 'Current clauses'}</span></div>{!selected && <p className="empty-evidence">Compare exact clauses here after retrieval.</p>}{selected && <KnowledgeDiff source={selected} items={data.sources} question={data.question} result={result} inspect={inspect} />}</div><div className="trust-column"><div className="column-heading"><h2>Trust breakdown</h2>{selected && <span className="total-score">{result.scores[selected.id].toFixed(1)} / 100</span>}</div>{!selected && <p className="empty-evidence">Trust contributions appear only for retrieved sources.</p>}{selected && <TrustBreakdown source={selected} factors={result.factors[selected.id]} total={result.scores[selected.id]} />}</div></div>
  {data.escalation && <section className="escalation-panel panel"><h2>{data.escalation.status === 'open' ? `Owner review · ${data.escalation.owner}` : 'Owner resolution recorded'}</h2><p>{data.escalation.reason}</p>{data.escalation.status === 'open' && session.capabilities.canResolve && result.validSources.length > 0 ? <form onSubmit={resolve}><label>Applicable clause<select name="sourceId" value={resolutionSource || result.top?.id || ''} onChange={e => setResolutionSource(e.target.value)}>{result.validSources.map(source => <option key={source.id} value={source.id}>{source.title} · {source.owner}</option>)}</select></label><label>Resolution reason<input name="reason" required minLength={3} maxLength={500} placeholder="Explain the owner’s decision" /></label><button className="button button-secondary" type="submit">Resolve escalation</button></form> : <p>{data.escalation.status === 'resolved' ? data.escalation.resolutionReason : !result.validSources.length ? 'Find sufficient evidence before this review can be resolved.' : 'A Reviewer or Admin can record the owner’s resolution.'}</p>}</section>}
  <RecommendationBanner result={result} capabilities={session.capabilities} onEscalate={onEscalate} onValidate={onValidate} escalationOpen={data.escalation?.status === 'open'} /><details className="rejected-sources"><summary>{result.excludedSources.length} sources excluded as current authority</summary><ul>{result.excludedSources.map(({ source, reasons }) => <li key={source.id}><strong>{source.title}</strong><span>{reasons.join(' ')}</span></li>)}</ul></details></>;
}
