import { Info, Link2 } from 'lucide-react';
import type { Scenario, Source } from '../data/scenario';
import type { Evaluation } from '../lib/scoring';
export function KnowledgeDiff({ source, items, question, result, inspect }: { source: Source; items: Source[]; question: Scenario; result: Evaluation; inspect: (s: Source) => void }) {
  const current = result.top ?? source;
  const comparison = source.id === current.id ? items.find(s => s.id !== current.id && s.country === current.country && s.flags.includes('outdated')) ?? result.validSources.find(s => s.id !== current.id && s.kind === 'document' && s.stance !== current.stance) ?? source : source;
  const oldPayroll = comparison.flags.includes('outdated') && comparison.stance === 'no-signoff-day15' && current.stance === 'retroactive-day20';
  const priorApproval = result.conflictCount > 0;
  const difference = priorApproval ? 'Two current clauses disagree' : oldPayroll ? 'Clause delta: +5 days' : result.flags.includes('Verified answer reused') ? 'Verified resolution vs. source wording' : 'Context and authority comparison';
  return <section key={source.id} className="diff-panel panel" aria-label="Legal redline"><div className="diff-top"><p className="eyebrow">{oldPayroll ? 'Superseded wording / current clause' : priorApproval ? 'Current policy / current agreement' : result.top ? 'Source wording / recommended clause' : 'Source wording / inspected clause'}</p><span>{difference}</span></div><div className="claim-grid"><article className="claim deprecated"><div className="claim-heading"><span>{oldPayroll ? '▲ Superseded · 2023' : priorApproval ? '↔ Disagreeing clause' : comparison.kind === 'verified' ? '! Previous review' : 'Source clause'}</span></div><p className="clause-reference">{comparison.reference}</p><p>{oldPayroll || priorApproval ? <del>{comparison.claim}</del> : comparison.claim}</p><button className="reference-link" onClick={() => inspect(comparison)}><Link2 size={16} />Read source</button></article><article className="claim current"><div className="claim-heading"><span>{!result.top ? '○ Unvalidated source clause' : priorApproval ? '↔ Current clause' : current.kind === 'verified' ? '✓ Verified answer' : '✓ Current policy'}</span></div><p className="clause-reference">{current.reference}</p><p><ins>{current.claim}</ins></p><button className="reference-link" onClick={() => inspect(current)}><Link2 size={16} />Read source</button></article></div><div className="discrepancy"><Info size={19} /><div><strong>{result.conflictCount ? 'Unresolved disagreement' : 'Review note'}</strong><p>{result.flags.includes('Verified answer reused') ? 'The current verified answer is reused as high-authority evidence. The prior clauses remain visible for traceability.' : result.resolvedSourceId ? 'An owner resolution selected this clause. Validate it with a future review date to make it reusable.' : source.discrepancy}</p></div></div><div className="diff-footer">{question.supersededOn && <span>Superseded: {question.supersededOn}</span>}<span>Reference hash: #{source.hash}</span></div></section>;
}
