import { useState, type FormEvent } from 'react';
import { ShieldCheck } from 'lucide-react';
import { login } from '../lib/api';
const accounts = [{ email: 'reader@trustlens.demo', password: 'ReaderDemo!', label: 'Reader · inspect decisions and cards' }, { email: 'reviewer@trustlens.demo', password: 'ReviewerDemo!', label: 'Reviewer · validate, escalate and resolve' }, { email: 'admin@trustlens.demo', password: 'AdminDemo!', label: 'Admin · all review actions and audit access' }];
export function Login({ onLogin }: { onLogin: () => void }) {
  const [email, setEmail] = useState(accounts[1].email); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (busy) return; setBusy(true); const result = await login(email, password); setBusy(false); if (result.ok) onLogin(); else setError(result.error.message); }
  return <main className="login-page"><section className="login-panel panel"><a className="brand" href="#login-title"><span className="brand-mark"><ShieldCheck /></span>TrustLens</a><p className="eyebrow">Find it. Understand it. Trust it.</p><h1 id="login-title">A clearer answer starts with accountable knowledge.</h1><p>Sign in to the Acme NV demo workspace. Your account determines your role and tenant.</p><form onSubmit={submit}><label>Email<input name="email" type="email" autoComplete="username" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Demo password<input name="password" type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <p className="login-error" role="alert">{error}</p>}<button type="submit" disabled={busy} className="button button-primary">{busy ? 'Signing in…' : 'Sign in'}</button></form><div className="login-accounts"><h2>Demo accounts</h2>{accounts.map(account => <div key={account.email}><button onClick={() => { setEmail(account.email); setPassword(account.password); setError(''); }}>{account.email}</button><p>{account.label}</p><code>{account.password}</code></div>)}</div><p className="muted">Public demo passwords · mock hash comparison · in-memory session. This is not production authentication. The local server holds demo sessions and data; restarting it restores the seeds.</p></section></main>;
}

