import { useEffect, useState } from 'react';
import { Building2, CalendarDays, ListChecks, RotateCcw } from 'lucide-react';
import type { Scenario } from '../data/scenario';
import type { Evaluation } from '../lib/scoring';
const guide = ['Open ticket', 'Check sources', 'Compare clauses', 'Inspect trust', 'Validate / escalate', 'Reuse verified answer'];
export function QuestionCard({ question, tickets, result, count, onTicket, onReset, canReset, busy = false }: { question: Scenario; tickets: Scenario[]; result: Evaluation; count: number; onTicket: (id: string) => void; onReset: () => void; canReset: boolean; busy?: boolean }) {
  const [guideOpen, setGuideOpen] = useState(false); const [step, setStep] = useState(0);
  useEffect(() => { if (!guideOpen) return; const handler = (event: KeyboardEvent) => { const target = event.target; const typing = target instanceof HTMLElement && !!target.closest('input,textarea,select,[contenteditable="true"]'); if (event.key.toLowerCase() === 'n' && !event.repeat && !event.ctrlKey && !event.metaKey && !event.altKey && !typing) { event.preventDefault(); setStep(current => (current + 1) % guide.length); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [guideOpen]);
  return <section className="question-card" aria-labelledby="question"><div className="ticket-tabs" aria-label="Tickets">{tickets.map(ticket => <button key={ticket.id} className={question.id === ticket.id ? 'active' : ''} aria-pressed={question.id === ticket.id} onClick={() => onTicket(ticket.id)}>{ticket.title}</button>)}</div><div className="question-top"><p className="eyebrow"><ListChecks size={18} />Payroll compliance inquiry · Ticket #{question.ticket}</p><span className={`analysis-badge ${result.state === 'confident' ? 'green' : 'amber'}`}>{result.confidenceLabel}</span></div><h1 id="question">{question.question}</h1><div className="context-row"><div className="context-controls"><span className="context-select">{question.context.countryCode} · {question.context.country}</span><span className="context-select"><Building2 size={17} />{question.context.customer}</span><span className="context-select"><CalendarDays size={17} />Payroll year {question.context.year}</span></div><div className="question-actions"><span>Sources loaded: {count}</span><button className="button button-secondary" aria-expanded={guideOpen} onClick={() => setGuideOpen(open => !open)}>Demo guide</button>{canReset && <button className="button button-secondary" disabled={busy} onClick={onReset}><RotateCcw size={16} />Reset demo</button>}</div></div>{guideOpen && <div className="demo-guide"><ol>{guide.map((label, index) => <li key={label} aria-current={step === index ? 'step' : undefined} className={step === index ? 'active' : ''}>{label}</li>)}</ol><div aria-live="polite">Step {step + 1}: {guide[step]} · Press N or <button onClick={() => setStep(current => (current + 1) % guide.length)}>Next step</button></div></div>}</section>;
}
