import { useEffect, useState } from 'react';
import type { Factor, Flag, Source } from '../data/scenario';
import { cardStatus, factorKeys, weights } from '../lib/scoring';
const flagLabels: Record<Flag, string> = { approved: '✓ Approved', outdated: '▲ Outdated', conflicts: '↔ Superseded wording', wrong_country: '✕ Wrong country', no_owner: '○ No owner', unverified: '? Unverified', expired: '! Expired', verified: '✓ Verified' };
export function SourceCard({ source, selected, onSelect, value, factors, excluded, highlighted = false, disabled = false }: { source: Source; selected: boolean; onSelect: () => void; value: number; factors: Record<Factor, number>; excluded: boolean; highlighted?: boolean; disabled?: boolean }) {
  const [display, setDisplay] = useState(value);
  useEffect(() => { if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) { setDisplay(value); return; } let frame: number; const start = performance.now(); const tick = (now: number) => { const progress = Math.min(1, (now - start) / 200); setDisplay(value * progress); if (progress < 1) frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [value]);
  return <button className={`source-card ${selected ? 'is-selected' : ''} ${highlighted ? 'is-recommended' : ''}`} data-source-id={source.id} disabled={disabled} onClick={onSelect} aria-pressed={selected} aria-label={`Inspect ${source.title}, score ${Math.round(value)}, ${excluded ? 'excluded' : 'eligible'}`}><div className="source-copy"><div className="source-flags"><span className="country-code">{source.country}</span>{source.flags.map(flag => <span key={flag} className={`flag flag-${flag}`}>{flagLabels[flag]}</span>)}{source.reviewBy && cardStatus(source.reviewBy) === 'expired' && !source.flags.includes('expired') && <span className="flag flag-expired">! Expired</span>}</div><h3>{source.title}</h3><div className="source-meta"><span>{source.owner ? `Owner: ${source.owner}` : 'Source: Internal chat export'}</span><time>{source.date}</time></div></div><div className="score-meter"><strong className="score-number">{Math.round(display)}</strong><div className="score-segments" role="img" aria-label={`Weighted contributions: ${factorKeys.map(key => `${key} ${(factors[key] * weights[key]).toFixed(1)}`).join(', ')}`}>{Array.from({ length: 20 }, (_, index) => { const point = index * 5; let sum = 0; const factor = factorKeys.find(key => { sum += factors[key] * weights[key]; return point < sum; }); return <span key={index} className={`score-segment ${factor ? `segment-${factor}` : 'segment-empty'}`} />; })}</div><span className="score-factor-labels">context | authority | freshness | corroboration</span></div></button>;
}
