import { useEffect, useRef, useState, type FormEvent } from 'react';
import { CircleCheck, X } from 'lucide-react';
import type { Source } from '../data/scenario';
import { reviewDateBounds } from '../lib/scoring';
import type { ApiError, ValidationInput } from '../lib/api';
export function ValidateModal({ source, onClose, onSubmit }: { source: Source; onClose: () => void; onSubmit: (input: ValidationInput) => Promise<ApiError | null> }) {
  const dialog = useRef<HTMLDialogElement>(null); const submitting = useRef(false); const [error, setError] = useState<ApiError | null>(null); const bounds = reviewDateBounds(); const [busy, setBusy] = useState(false);
  useEffect(() => { const element = dialog.current!; const previous = document.activeElement as HTMLElement; element.showModal(); return () => { element.close(); previous?.focus(); }; }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (submitting.current) return; submitting.current = true; setBusy(true); try { setError(await onSubmit({ questionId: source.questionId, sourceId: source.id, claim: String(data.get('claim') ?? ''), reason: String(data.get('reason') ?? ''), owner: String(data.get('owner') ?? ''), reviewBy: String(data.get('reviewBy') ?? '') })); } catch { setError({ code: 'CONFLICT', message: 'The answer could not be saved. Please try again.' }); } finally { submitting.current = false; setBusy(false); } }
  return <dialog ref={dialog} className="validate-modal" aria-labelledby="validate-heading" onCancel={e => { e.preventDefault(); if (!submitting.current) onClose(); }}><div className="modal-heading"><div><span className="eyebrow">Create a verified knowledge card</span><h2 id="validate-heading">Validate this answer</h2></div><button className="icon-button" aria-label="Close validation" disabled={busy} onClick={onClose}><X /></button></div><p className="modal-intro">The source clause and accountable owner are fixed. Add your review reason and next review date.</p><form onSubmit={submit} noValidate><label>Claim<textarea name="claim" readOnly rows={3} value={source.claim} /></label><label>Reason for validation<textarea name="reason" required minLength={3} maxLength={500} rows={3} placeholder="Why is this clause applicable?" aria-invalid={error?.field === 'reason'} /></label><div className="form-row"><label>Accountable owner<input name="owner" readOnly value={source.owner ?? ''} /></label><label>Required review-by date<input name="reviewBy" type="date" required min={bounds.min} max={bounds.max} aria-invalid={error?.field === 'reviewBy'} /></label></div>{error && <p className="form-error" role="alert">{error.code}: {error.message}</p>}<div className="modal-actions"><button className="button button-secondary" type="button" disabled={busy} onClick={onClose}>Cancel</button><button className="button button-primary" type="submit" disabled={busy}><CircleCheck size={18} />{busy ? 'Saving…' : 'Create verified card'}</button></div></form></dialog>;
}
