import { useEffect, useRef, useState, type FormEvent } from 'react';
import { CircleCheck, X } from 'lucide-react';
import type { Source, VerifiedCard } from '../data/scenario';
import { dateKey, validateCardInput } from '../lib/scoring';
export type ValidationInput = Pick<VerifiedCard, 'claim' | 'reason' | 'owner' | 'reviewBy'>;
export function ValidateModal({ source, onClose, onSubmit }: { source: Source; onClose: () => void; onSubmit: (input: ValidationInput) => string | null }) {
  const dialog = useRef<HTMLDialogElement>(null); const [error, setError] = useState('');
  useEffect(() => { const element = dialog.current!; const previous = document.activeElement as HTMLElement; element.showModal(); return () => { element.close(); previous?.focus(); }; }, []);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const input = { claim: String(data.get('claim') ?? '').trim(), reason: String(data.get('reason') ?? '').trim(), owner: String(data.get('owner') ?? '').trim(), reviewBy: String(data.get('reviewBy') ?? '') }; const issue = validateCardInput(input) || onSubmit(input); if (issue) setError(issue); }
  return <dialog ref={dialog} className="validate-modal" aria-labelledby="validate-heading" onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === dialog.current) { const rect = dialog.current.getBoundingClientRect(); if (e.clientX < rect.left || e.clientX > rect.right || e.clientY < rect.top || e.clientY > rect.bottom) onClose(); } }}><div className="modal-heading"><div><span className="eyebrow">Create a verified knowledge card</span><h2 id="validate-heading">Validate this answer</h2></div><button className="icon-button" aria-label="Close validation" onClick={onClose}><X /></button></div><p className="modal-intro">Capture the decision, its accountable owner, and when it must be reviewed again.</p><form onSubmit={submit}><label>Claim<textarea name="claim" required maxLength={2000} rows={4} defaultValue={source.claim} autoFocus /></label><label>Reason for validation<textarea name="reason" required maxLength={1000} rows={3} placeholder="Why is this the right answer for this customer?" /></label><div className="form-row"><label>Accountable owner<input name="owner" required maxLength={120} defaultValue={source.owner ?? ''} /></label><label>Required review-by date<input name="reviewBy" type="date" required min={dateKey()} /></label></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button className="button button-secondary" type="button" onClick={onClose}>Cancel</button><button className="button button-primary" type="submit"><CircleCheck size={18} />Create verified card</button></div></form></dialog>;
}
